name: 'Linter check'

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16, 18]
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn' # cache node modules
          node-version: ${{ matrix.node }}
      - run: corepack enable
      - run: yarn
      - run: yarn run sdk:lint # lint code
      - run: yarn run sdk:build # compile typescript into javascript
      - run: yarn run sdk:test:unit --silent --coverage # run unit tests
      # - run: yarn run test:integrations # run integration tests tests
      - name: Build docs
        run: npm run docs
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: docs